import { Box, Button, color, Heading, SimpleGrid } from "@chakra-ui/react";
import { mode } from "@chakra-ui/theme-tools";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = (props) => {
  const color = mode("black", "white")(props);
  console.log("color", color);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading size="3xl" as="h1">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Heading>
        <SimpleGrid
          columns={{ sm: 2, md: 4 }}
          spacing="8"
          p="10"
          textAlign="center"
          rounded="lg"
          color="black"
        >
          <Box boxShadow="sm" p="6" rounded="md" bg="gray.100">
            sm
          </Box>

          <Box boxShadow="md" p="6" rounded="md" bg="gray.100">
            md
          </Box>
          <Box boxShadow="lg" p="6" rounded="md" bg="gray.100">
            lg
          </Box>

          <Box boxShadow="outline" p="6" rounded="md" bg="gray.100">
            Outline
          </Box>

          <Box rounded="md">
            <Button>getting started</Button>
            <Button variant="outline">more info</Button>
            <Button variant="link">more info</Button>
            <Button variant="ghost">more info</Button>
            <Button variant="solid">more info</Button>
            <Button variant="ptnPrimary">more info</Button>
            <Button variant="ptnSecondary">more info</Button>
          </Box>
        </SimpleGrid>

        <p>
          Get <strong>started</strong> by editing <code>pages/index.tsx</code>
        </p>

        <div>
          <a href="https://nextjs.org/docs">
            <Heading as="h2">Documentation &rarr;</Heading>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <Heading as="h2">Learn &rarr;</Heading>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples">
            <Heading as="h2">Examples &rarr;</Heading>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <Heading as="h2">Deploy &rarr;</Heading>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by vercel
        </a>
      </footer>
    </div>
  );
};

export default Home;
